// Mocks generated by Mockito 5.4.5 from annotations
// in swypex_task/test/features/exchange_rates/presentation/cubit/exchange_rates_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:swypex_task/core/errors/failures.dart' as _i6;
import 'package:swypex_task/features/exchange_rates/domain/entities/exchange_rates_entity.dart'
    as _i7;
import 'package:swypex_task/features/exchange_rates/domain/repositories/exchange_rates_repository.dart'
    as _i2;
import 'package:swypex_task/features/exchange_rates/domain/usecases/get_exchange_rates.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeExchangeRatesRepository_0 extends _i1.SmartFake
    implements _i2.ExchangeRatesRepository {
  _FakeExchangeRatesRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetExchangeRates].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetExchangeRates extends _i1.Mock implements _i4.GetExchangeRates {
  MockGetExchangeRates() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ExchangeRatesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeExchangeRatesRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ExchangeRatesRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.ExchangeRatesEntity>> call(
    _i4.ExchangeRatesParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<
              _i3.Either<_i6.Failure, _i7.ExchangeRatesEntity>
            >.value(
              _FakeEither_1<_i6.Failure, _i7.ExchangeRatesEntity>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.ExchangeRatesEntity>>);
}
